country_map = {
    "Mexiko": "Mexico",
    "Frankreich": "France",
    "Deutschland": "Germany",
    "Italien": "Italy",
    "Russland": "Russia",
    "Österreich": "Austria",
    "Niederlande": "Netherlands",
    "Finnland": "Finland",
    "Ungarn": "Hungary",
    "Philippinen": "Philippines",
    "Spanien": "Spain",
    "Polen": "Poland",
    "Belgien": "Belgium",
    "Südkorea": "South Korea",
    "Schweiz": "Switzerland",
    "Indien": "India",
    "Japan in Kawasaki Stadium": "Japan",
    "Dänemark": "Denmark",
    "Estland": "Estonia",
}
